name: Continuous Integration PR Tests

on:
  pull_request:
    types: [opened, synchronize]
    branches: main

jobs:
  client_tests:
    name: Client Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node Environment
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Linter
        run: yarn lint

      - name: Run Typecheck
        run: yarn type-check

      - name: Run Tests
        run: yarn test

      - name: Run Prebuild
        run: |
          if ! npx expo-doctor; then
            echo "Prebuild checks failed"
            exit 1
          fi
          echo "prebuild_sucess=true" >> $GITHUB_OUTPUT

  build:
    needs: client_tests
    name: IOS Build
    runs-on: ubuntu-latest

    steps:
      - eas/checkout

      - eas/install_node_modules

      - eas/resolve_build_config

      - eas/prebuild

      - run:
          name: Install pods
          working_directory: ./ios
          command: pod install

      - eas/generate_gymfile_from_template

      - eas/run_fastlane

      - eas/find_and_upload_build_artifacts
