name: Continuous Integration PR Tests

on:
  pull_request:
    types: [opened, synchronize]
    branches: main

env:
  EXPO_VERSION: '0.18.31'
  EAS_VERSION: '13.1.1'

jobs:
  client_tests:
    name: Client Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node Environment
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Linter
        run: yarn lint

      - name: Run Typecheck
        run: yarn type-check

      - name: Run Tests
        run: yarn test

      - name: Run Prebuild
        run: npx expo-doctor

  build_ios:
    name: Build IOS Client
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node Environment
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install EAS Dependencies
        run: |
          yarn global add eas-cli@13.1.1
          yarn add expo@51.0.39
          yarn add expo-dev-client@4.0.28

      - name: Build Client
        run: eas build --platform ios --profile development --local --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}


  build_android:
    name: Build Android Client
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install EAS Dependencies
        run: |
          yarn global add eas-cli@13.1.1
          yarn add expo@51.0.39

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Client
        run: eas build --platform android --profile preview --local --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          GRADLE_OPTS: >-
            -Dorg.gradle.daemon=false
            -Dorg.gradle.parallel=true
            -Dorg.gradle.workers.max=2
            -Dorg.gradle.caching=true
